### ISSUE TITLE
best path for learning java libraries

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#1054]
Take a look [here](https://my.mindnode.com/bqqerP7QMhU9pDir4XaksndsmbTraUBQ4otAGtez).

If you think there is a better way one can learn java libraries or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on java libraries that are missing or you wish something was added, you can say it here.

**Comment by jonk1993** [comment]
Might be helpful to add more categories of frameworks, like: Testing (JUnit) and Core (Guava, apache-commons).

Also would including a node with a reference to build systems be helpful? Since if someone actually wants to _use_ java libraries, they must import them in some way (Gradle, Maven, Ant). Or is this too detached from the topic "java libraries"?

**Comment by nikitavoloboev** [comment]
Added them. Thank you @jonk1993
