### ISSUE TITLE
best path for learning category theory

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#606]
Take a look [here](https://my.mindnode.com/cgWrEEoW3HSA2iysGp2swqphQXSpqVvM5TaismpM#-59.7,224.9,2).

If you think there is a better way one can learn category theory or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on category theory that are missing or you wish something was added, you can say it here.

**Comment by Nuriaion** [comment]
In my opinion one of the best introduction to category theory ist: https://youtu.be/I8LbkfSSR58?list=PLbgaMIhjbmEnaH_LTkxLI7FMa2HsnawM_

**Comment by nikitavoloboev** [comment]
I actually link to it already @Nuriaion 

Check 2. category theory lectures node. :)

**Comment by Nuriaion** [comment]
Oh sorry. I haven't looked good enough...

**Comment by wisn** [comment]
This issue seems duplicated with https://github.com/nikitavoloboev/learn-anything/issues/473
I think [here](https://ncatlab.org/nlab/show/category+theory) is a great source for category theory. I mean, nLab have a really great resource of mathematics, physics, and philosophy.

**Comment by nikitavoloboev** [comment]
I added it @wisn 

Thank you 💙

**Comment by wisn** [comment]
There is a [glossary of category theory](https://en.wikipedia.org/wiki/Glossary_of_category_theory) in Wikipedia. I think I will contributes on this field.

**Comment by nikitavoloboev** [comment]
That would be amazing.

If you want you can write it here too and I will add it since it's still a bit hard to add things manually to JSON's. We are working on it. :)

**Comment by wisn** [comment]
Well, I will try to use [learn-anything/react-mindmap](https://github.com/learn-anything/react-mindmap) later.

The basic should be
- [Category](https://ncatlab.org/nlab/show/category)
- [Functor](https://ncatlab.org/nlab/show/functor)
- [Natural transformation](https://ncatlab.org/nlab/show/natural+transformation)

I think `profunctor` a little bit beyond for the `basic` part. It's part of [enriched category theory](https://ncatlab.org/nlab/show/enriched+category+theory).

---

The `category` part will have a `basic` part as shown below
- [Category itself](https://ncatlab.org/nlab/show/category)
- [Object](https://ncatlab.org/nlab/show/object)
- [Morphism](https://ncatlab.org/nlab/show/morphism)
- [Cat](https://ncatlab.org/nlab/show/Cat)

For the article reference, please add nLab articles. They have a useful lecture note about mathematics stuff.

---

The `functor` part will have a `basic` part as shown below
- [Functor itself](https://ncatlab.org/nlab/show/functor)

I just know one for now.

---

I still have no idea about `natural transformation` since I just read it recently.

---

Feel free to correct me if I'm wrong. Should we divide category theory, enriched category theory, and higher category theory?

I will ask some helps for someone who knew more about this as well.

**Comment by wisn** [comment]
For addition, [`stuff, structure, and properties`](https://ncatlab.org/nlab/show/stuff%2C+structure%2C+property) will be the child of `functor` as well as [`contravariant functor`](https://ncatlab.org/nlab/show/contravariant+functor).

**Comment by nikitavoloboev** [comment]
I have added it to [category theory](https://learn-anything.xyz/mathematics/category-theory). Can you take a look? Is that what you meant?

I am really new to category theory but really want to learn it one day so not sure how to best structure it.

**Comment by wisn** [comment]
Looks great! Well, creating `best path for learning` is not easy. At least there is some addition to category theory. I will comes back later after read some more.
