### ISSUE TITLE
best path for learning open source

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#704]
Take a look [here](https://my.mindnode.com/i2KJsa46DzxEMaziscL7xMzJMxqAtnNFNAXaJ6d1).

If you think there is a better way one can learn open source or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on open source that are missing or you wish something was added, you can say it here.

**Comment by Blake575** [comment]
I'm new to open source (started yesterday) and got interested because this project is something I think is truly valuable. I'm still stumbling my way around but I found these two videos to be helpful:

[Contributing to Open Source Part I: The Easy Way](https://youtu.be/V74l_zS1x8E)

[Contributing to Open Source Part II: The Real Way](https://youtu.be/mENDYhfxH-o)

**Comment by nikitavoloboev** [comment]
Thank you @Blake575 

I am really happy you find value in this search. 💙

If you want, you can join our [Slack community](https://knowledge-map.slack.com/shared_invite/MTgxNTYzMjIzNjM5LTE0OTQzMzA4MDAtYzY1YWY0ZDc0NQ). :)

**Comment by Jp-Rivera** [comment]
I found [this article](https://medium.freecodecamp.com/a-beginners-very-bumpy-journey-through-the-world-of-open-source-4d108d540b39) to be very helpful while needed some open source guidance.
